mutation SignUp($input: RegisterUserInput!) {
    registerUser(input: $input) {
        success
        message
        errors
        user {
            id
            firstName
            lastName
            email
            emailVerified
            mfaEnabled
            isActive
            profile {
                profileImage
                bio
                profession
                address
                phoneNumber
                profession
                gender
                dateOfBirth
            }
        }
    }
}